[2023-11-09T19:06:41.247+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customers.save_customers_to_excel manual__2023-11-09T19:06:33.475785+00:00 [queued]>
[2023-11-09T19:06:41.264+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customers.save_customers_to_excel manual__2023-11-09T19:06:33.475785+00:00 [queued]>
[2023-11-09T19:06:41.265+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-11-09T19:06:41.266+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-11-09T19:06:41.267+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-11-09T19:06:41.288+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): save_customers_to_excel> on 2023-11-09 19:06:33.475785+00:00
[2023-11-09T19:06:41.294+0000] {standard_task_runner.py:55} INFO - Started process 13340 to run task
[2023-11-09T19:06:41.297+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'customers', 'save_customers_to_excel', 'manual__2023-11-09T19:06:33.475785+00:00', '--job-id', '223', '--raw', '--subdir', 'DAGS_FOLDER/customer_1.py', '--cfg-path', '/tmp/tmp7ict_der']
[2023-11-09T19:06:41.299+0000] {standard_task_runner.py:83} INFO - Job 223: Subtask save_customers_to_excel
[2023-11-09T19:06:41.368+0000] {task_command.py:389} INFO - Running <TaskInstance: customers.save_customers_to_excel manual__2023-11-09T19:06:33.475785+00:00 [running]> on host 9dcc097b8292
[2023-11-09T19:06:41.616+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=customers
AIRFLOW_CTX_TASK_ID=save_customers_to_excel
AIRFLOW_CTX_EXECUTION_DATE=2023-11-09T19:06:33.475785+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-09T19:06:33.475785+00:00
[2023-11-09T19:06:41.626+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-11-09T19:06:41.678+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-11-09T19:06:41.688+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/customer_1.py", line 81, in _save_customers_to_excel
    ws.cell(row=r_idx, column=c_idx, value=value)
  File "/home/airflow/.local/lib/python3.7/site-packages/openpyxl/worksheet/worksheet.py", line 247, in cell
    cell.value = value
AttributeError: 'MergedCell' object attribute 'value' is read-only
[2023-11-09T19:06:41.711+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=customers, task_id=save_customers_to_excel, execution_date=20231109T190633, start_date=20231109T190641, end_date=20231109T190641
[2023-11-09T19:06:41.731+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 223 for task save_customers_to_excel ('MergedCell' object attribute 'value' is read-only; 13340)
[2023-11-09T19:06:41.751+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-11-09T19:06:41.772+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
