[2023-11-09T19:05:16.329+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customers.save_customers_to_excel manual__2023-11-09T19:05:09.260929+00:00 [queued]>
[2023-11-09T19:05:16.343+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customers.save_customers_to_excel manual__2023-11-09T19:05:09.260929+00:00 [queued]>
[2023-11-09T19:05:16.344+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-11-09T19:05:16.345+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-11-09T19:05:16.346+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-11-09T19:05:16.364+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): save_customers_to_excel> on 2023-11-09 19:05:09.260929+00:00
[2023-11-09T19:05:16.371+0000] {standard_task_runner.py:55} INFO - Started process 13246 to run task
[2023-11-09T19:05:16.374+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'customers', 'save_customers_to_excel', 'manual__2023-11-09T19:05:09.260929+00:00', '--job-id', '220', '--raw', '--subdir', 'DAGS_FOLDER/customer_1.py', '--cfg-path', '/tmp/tmp4dl_aipz']
[2023-11-09T19:05:16.376+0000] {standard_task_runner.py:83} INFO - Job 220: Subtask save_customers_to_excel
[2023-11-09T19:05:16.450+0000] {task_command.py:389} INFO - Running <TaskInstance: customers.save_customers_to_excel manual__2023-11-09T19:05:09.260929+00:00 [running]> on host 9dcc097b8292
[2023-11-09T19:05:16.710+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=customers
AIRFLOW_CTX_TASK_ID=save_customers_to_excel
AIRFLOW_CTX_EXECUTION_DATE=2023-11-09T19:05:09.260929+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-09T19:05:09.260929+00:00
[2023-11-09T19:05:16.720+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-11-09T19:05:16.771+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-11-09T19:05:16.780+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/customer_1.py", line 81, in _save_customers_to_excel
    ws.cell(row=r_idx, column=c_idx, value=value)
  File "/home/airflow/.local/lib/python3.7/site-packages/openpyxl/worksheet/worksheet.py", line 247, in cell
    cell.value = value
AttributeError: 'MergedCell' object attribute 'value' is read-only
[2023-11-09T19:05:16.795+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=customers, task_id=save_customers_to_excel, execution_date=20231109T190509, start_date=20231109T190516, end_date=20231109T190516
[2023-11-09T19:05:16.814+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 220 for task save_customers_to_excel ('MergedCell' object attribute 'value' is read-only; 13246)
[2023-11-09T19:05:16.867+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-11-09T19:05:16.888+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
