[2023-11-02T10:55:39.893+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: test_dag_tutorial.create_postgres_table scheduled__2020-02-05T00:00:00+00:00 [queued]>
[2023-11-02T10:55:39.917+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: test_dag_tutorial.create_postgres_table scheduled__2020-02-05T00:00:00+00:00 [queued]>
[2023-11-02T10:55:39.922+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-11-02T10:55:39.924+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-11-02T10:55:39.925+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-11-02T10:55:40.092+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2020-02-05 00:00:00+00:00
[2023-11-02T10:55:40.100+0000] {standard_task_runner.py:55} INFO - Started process 1479 to run task
[2023-11-02T10:55:40.111+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'test_dag_tutorial', 'create_postgres_table', 'scheduled__2020-02-05T00:00:00+00:00', '--job-id', '250', '--raw', '--subdir', 'DAGS_FOLDER/test_dag_tutorial.py', '--cfg-path', '/tmp/tmpigidoalp']
[2023-11-02T10:55:40.120+0000] {standard_task_runner.py:83} INFO - Job 250: Subtask create_postgres_table
[2023-11-02T10:55:40.358+0000] {task_command.py:376} INFO - Running <TaskInstance: test_dag_tutorial.create_postgres_table scheduled__2020-02-05T00:00:00+00:00 [running]> on host 1dfdc0df4852
[2023-11-02T10:55:40.568+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=tetiana
AIRFLOW_CTX_DAG_ID=test_dag_tutorial
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2020-02-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-02-05T00:00:00+00:00
[2023-11-02T10:55:40.641+0000] {base.py:71} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-11-02T10:55:40.655+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 288, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 115, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

[2023-11-02T10:55:40.696+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=test_dag_tutorial, task_id=create_postgres_table, execution_date=20200205T000000, start_date=20231102T105539, end_date=20231102T105540
[2023-11-02T10:55:40.755+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 250 for task create_postgres_table (connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
; 1479)
[2023-11-02T10:55:40.786+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-11-02T10:55:40.898+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-02T10:59:34.480+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: test_dag_tutorial.create_postgres_table scheduled__2020-02-05T00:00:00+00:00 [queued]>
[2023-11-02T10:59:34.510+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: test_dag_tutorial.create_postgres_table scheduled__2020-02-05T00:00:00+00:00 [queued]>
[2023-11-02T10:59:34.513+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-11-02T10:59:34.515+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-11-02T10:59:34.516+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-11-02T10:59:34.669+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2020-02-05 00:00:00+00:00
[2023-11-02T10:59:34.702+0000] {standard_task_runner.py:55} INFO - Started process 1853 to run task
[2023-11-02T10:59:34.706+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'test_dag_tutorial', 'create_postgres_table', 'scheduled__2020-02-05T00:00:00+00:00', '--job-id', '358', '--raw', '--subdir', 'DAGS_FOLDER/test_dag_tutorial.py', '--cfg-path', '/tmp/tmpa0n05mcv']
[2023-11-02T10:59:34.725+0000] {standard_task_runner.py:83} INFO - Job 358: Subtask create_postgres_table
[2023-11-02T10:59:34.942+0000] {task_command.py:376} INFO - Running <TaskInstance: test_dag_tutorial.create_postgres_table scheduled__2020-02-05T00:00:00+00:00 [running]> on host 1dfdc0df4852
[2023-11-02T10:59:35.449+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=tetiana
AIRFLOW_CTX_DAG_ID=test_dag_tutorial
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2020-02-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-02-05T00:00:00+00:00
[2023-11-02T10:59:35.523+0000] {base.py:71} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-11-02T10:59:35.558+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 288, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 115, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "host.docker.internal" (192.168.65.254), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2023-11-02T10:59:35.651+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=test_dag_tutorial, task_id=create_postgres_table, execution_date=20200205T000000, start_date=20231102T105934, end_date=20231102T105935
[2023-11-02T10:59:35.893+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 358 for task create_postgres_table (connection to server at "host.docker.internal" (192.168.65.254), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 1853)
[2023-11-02T10:59:36.028+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-11-02T10:59:36.095+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
