[2023-11-04T20:50:40.283+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: people.read_people manual__2023-11-04T20:50:36.095372+00:00 [queued]>
[2023-11-04T20:50:40.296+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: people.read_people manual__2023-11-04T20:50:36.095372+00:00 [queued]>
[2023-11-04T20:50:40.297+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-11-04T20:50:40.298+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-11-04T20:50:40.299+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-11-04T20:50:40.319+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): read_people> on 2023-11-04 20:50:36.095372+00:00
[2023-11-04T20:50:40.326+0000] {standard_task_runner.py:55} INFO - Started process 3888 to run task
[2023-11-04T20:50:40.329+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'people', 'read_people', 'manual__2023-11-04T20:50:36.095372+00:00', '--job-id', '225', '--raw', '--subdir', 'DAGS_FOLDER/people.py', '--cfg-path', '/tmp/tmpzxy5_sib']
[2023-11-04T20:50:40.331+0000] {standard_task_runner.py:83} INFO - Job 225: Subtask read_people
[2023-11-04T20:50:40.404+0000] {task_command.py:376} INFO - Running <TaskInstance: people.read_people manual__2023-11-04T20:50:36.095372+00:00 [running]> on host 0ef3ea835a0e
[2023-11-04T20:50:40.524+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=people
AIRFLOW_CTX_TASK_ID=read_people
AIRFLOW_CTX_EXECUTION_DATE=2023-11-04T20:50:36.095372+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-04T20:50:36.095372+00:00
[2023-11-04T20:50:40.537+0000] {logging_mixin.py:120} INFO - Skipping row with non-numeric 'Index' value: 10,8e4FB470FE19bF0,Isaiah,Downs,Male,virginiaterrell@example.org,+1-511-372-1544x8206,1964-09-20,"Engineer, site"
[2023-11-04T20:50:40.539+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/people.py", line 30, in _read_people
    date_str = row[7]
IndexError: list index out of range
[2023-11-04T20:50:40.553+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=people, task_id=read_people, execution_date=20231104T205036, start_date=20231104T205040, end_date=20231104T205040
[2023-11-04T20:50:40.568+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 225 for task read_people (list index out of range; 3888)
[2023-11-04T20:50:40.581+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-11-04T20:50:40.604+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
