[2023-11-08T14:33:15.064+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: elastic_dag.print_es_info manual__2023-11-08T14:33:11.325531+00:00 [queued]>
[2023-11-08T14:33:15.080+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: elastic_dag.print_es_info manual__2023-11-08T14:33:11.325531+00:00 [queued]>
[2023-11-08T14:33:15.081+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-11-08T14:33:15.082+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-11-08T14:33:15.083+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-11-08T14:33:15.106+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): print_es_info> on 2023-11-08 14:33:11.325531+00:00
[2023-11-08T14:33:15.114+0000] {standard_task_runner.py:55} INFO - Started process 884 to run task
[2023-11-08T14:33:15.121+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'elastic_dag', 'print_es_info', 'manual__2023-11-08T14:33:11.325531+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/elastic_dag.py', '--cfg-path', '/tmp/tmpy2dqlfsn']
[2023-11-08T14:33:15.124+0000] {standard_task_runner.py:83} INFO - Job 39: Subtask print_es_info
[2023-11-08T14:33:15.216+0000] {task_command.py:389} INFO - Running <TaskInstance: elastic_dag.print_es_info manual__2023-11-08T14:33:11.325531+00:00 [running]> on host 1ca66c4fb7ea
[2023-11-08T14:33:15.315+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=elastic_dag
AIRFLOW_CTX_TASK_ID=print_es_info
AIRFLOW_CTX_EXECUTION_DATE=2023-11-08T14:33:11.325531+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-08T14:33:11.325531+00:00
[2023-11-08T14:33:15.318+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/elastic_dag.py", line 9, in _print_es_info
    hook = ESConnection(["http://elastic:9200"])
  File "/home/airflow/.local/lib/python3.7/site-packages/es/elastic/api.py", line 67, in __init__
    self.es = Elasticsearch(self.url, **self.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 207, in __init__
    self.transport = transport_class(_normalize_hosts(hosts), **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 51, in _normalize_hosts
    parsed_url = urlparse(host)
  File "/usr/local/lib/python3.7/urllib/parse.py", line 371, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
  File "/usr/local/lib/python3.7/urllib/parse.py", line 445, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL
[2023-11-08T14:33:15.336+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=elastic_dag, task_id=print_es_info, execution_date=20231108T143311, start_date=20231108T143315, end_date=20231108T143315
[2023-11-08T14:33:15.353+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 39 for task print_es_info (Invalid IPv6 URL; 884)
[2023-11-08T14:33:15.380+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-11-08T14:33:15.403+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
